#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.
import sys
import os

sys.path.insert(0, os.path.abspath('../../chronon'))


from dunamai import Version


extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.viewcode',
              'sphinx.ext.napoleon',
              'sphinx.ext.intersphinx',
              'sphinx.ext.mathjax',
              'sphinx.ext.todo',
              'sphinx.ext.ifconfig',
]

templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'
project = u'chronon'
copyright = u"2020, McLaren Applied"

version = str(Version.from_git())
release = version

exclude_patterns = ['_build']

pygments_style = 'sphinx'

import sphinx_rtd_theme
html_theme = 'sphinx_rtd_theme'
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

htmlhelp_basename = 'chronondoc'

autoclass_content = "both"

man_pages = [
    ('index', 'chronon',
     u'Chronon Documentation',
     [u'McLarenApplied'], 1)
]

texinfo_documents = [
    ('index', 'chronon',
     u'Chronon Documentation',
     u'McLarenApplied',
     'chronon',
     'Discrete Event Framework',
     'Miscellaneous'),
]

# -- Options for LaTeX output ------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #'preamble': '',
}

latex_documents = [
    ('index', 'chronon.tex',
     u'Chronon Documentation',
     u'McLaren Applied', 'manual'),
]
